function loadPosts()
{
	model.posts.push({
		'id':'welcome_coming_soon',
		'title':'Welcome!',
		'content':'Welcome to the Infinisheets site! We\'ve been hard at work on a simple new way to make math worksheets, and it\'s almost ready to share with you!<br /><br />Infinisheets is:<br /><ul><li><b>Fast</b> - make worksheets in just a few minutes</li><li><b>Easy to use</b> - adding problems is as easy as clicking!</li><li><b>Easy to grade</b> - each generated worksheet can be printed with the answer key</li><li><b>Customizable</b> - mix and match problem types and worksheet templates</li><li><b>Extendable</b> - We plan to add new problem types and worksheet templates with individually purchased bundles, check out <a href="http://www.teacherspayteachers.com/Store/Infinisheets">our store at TpT!</a></li><li><b>Reusable</b> - save either your worksheet type or the generated PDF to reuse year after year.</li></ul> Infinisheets is great for <i>multi-instructional use:</i><br /><ul><li><b>Whole Group Instruction</b> - Easily create worksheets to use with your entire class/group.</li><li><b>Tiered Instruction</b> - Easily target specific skills in your classroom and address needs of gifted, average and struggling learners with tiered worksheets.</li><li><b>Individualized Instruction</b> - Easily create individualized worksheets for every student in your classroom/group to target specific math skills.  Recommended for special education classrooms, intervention times and learning centers.</li></ul> Watch here for product announcements and video tutorials!<br />Also, feel free to email us at jessenkaren@gmail.com with any questions!'
		});
	model.posts.push({
		'id':'fast_fill',
		'title':'Fast Fill Mode',
		'content':'A quick demo showing how fast fill mode helps you make worksheets faster!<br /><iframe width="560" height="315" src="https://www.youtube.com/embed/XwkThSHn_nE" frameborder="0" allowfullscreen></iframe>'
		});
	model.posts.push({
		'id':'samples',
		'title':'Sample Worksheets',
		'content':'We just finished up a quick <a href="samples/Example%20Worksheets%201-6.pdf">sample</a> of some elementary math worksheets generated by Infinisheets - check it out!'
		});
	model.posts.push({
		'id':'sneak_peek',
		'title':'Sneak Peek!',
		'content':'Here\'s a short demo of Infinisheets that shows how to make customized worksheets for your students in just two minutes!<br /><iframe width="560" height="315" src="//www.youtube.com/embed/s1VeGXSfHPM?rel=0" frameborder="0" allowfullscreen></iframe>'
		});
}